/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var BasicTypes_pb = require('./BasicTypes_pb.js');
goog.exportSymbol('proto.proto.CreateFeeScheduleTransactionBody', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.CreateFeeScheduleTransactionBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.CreateFeeScheduleTransactionBody.repeatedFields_, null);
};
goog.inherits(proto.proto.CreateFeeScheduleTransactionBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.proto.CreateFeeScheduleTransactionBody.displayName = 'proto.proto.CreateFeeScheduleTransactionBody';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.CreateFeeScheduleTransactionBody.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.CreateFeeScheduleTransactionBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.CreateFeeScheduleTransactionBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CreateFeeScheduleTransactionBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: (f = msg.getKey()) && BasicTypes_pb.Key.toObject(includeInstance, f),
    transactionfeescheduleList: jspb.Message.toObjectList(msg.getTransactionfeescheduleList(),
    BasicTypes_pb.TransactionFeeSchedule.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.CreateFeeScheduleTransactionBody}
 */
proto.proto.CreateFeeScheduleTransactionBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.CreateFeeScheduleTransactionBody;
  return proto.proto.CreateFeeScheduleTransactionBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.CreateFeeScheduleTransactionBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.CreateFeeScheduleTransactionBody}
 */
proto.proto.CreateFeeScheduleTransactionBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new BasicTypes_pb.Key;
      reader.readMessage(value,BasicTypes_pb.Key.deserializeBinaryFromReader);
      msg.setKey(value);
      break;
    case 2:
      var value = new BasicTypes_pb.TransactionFeeSchedule;
      reader.readMessage(value,BasicTypes_pb.TransactionFeeSchedule.deserializeBinaryFromReader);
      msg.addTransactionfeeschedule(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.CreateFeeScheduleTransactionBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.CreateFeeScheduleTransactionBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CreateFeeScheduleTransactionBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      BasicTypes_pb.Key.serializeBinaryToWriter
    );
  }
  f = message.getTransactionfeescheduleList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      BasicTypes_pb.TransactionFeeSchedule.serializeBinaryToWriter
    );
  }
};


/**
 * optional Key key = 1;
 * @return {?proto.proto.Key}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.getKey = function() {
  return /** @type{?proto.proto.Key} */ (
    jspb.Message.getWrapperField(this, BasicTypes_pb.Key, 1));
};


/** @param {?proto.proto.Key|undefined} value */
proto.proto.CreateFeeScheduleTransactionBody.prototype.setKey = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.proto.CreateFeeScheduleTransactionBody.prototype.clearKey = function() {
  this.setKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.hasKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated TransactionFeeSchedule transactionFeeSchedule = 2;
 * @return {!Array<!proto.proto.TransactionFeeSchedule>}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.getTransactionfeescheduleList = function() {
  return /** @type{!Array<!proto.proto.TransactionFeeSchedule>} */ (
    jspb.Message.getRepeatedWrapperField(this, BasicTypes_pb.TransactionFeeSchedule, 2));
};


/** @param {!Array<!proto.proto.TransactionFeeSchedule>} value */
proto.proto.CreateFeeScheduleTransactionBody.prototype.setTransactionfeescheduleList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.TransactionFeeSchedule=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.TransactionFeeSchedule}
 */
proto.proto.CreateFeeScheduleTransactionBody.prototype.addTransactionfeeschedule = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.TransactionFeeSchedule, opt_index);
};


proto.proto.CreateFeeScheduleTransactionBody.prototype.clearTransactionfeescheduleList = function() {
  this.setTransactionfeescheduleList([]);
};


goog.object.extend(exports, proto.proto);
